import Link from "next/link"; import {Plus,Filter,CalendarDays} from "lucide-react"; import {query} from "../../lib/queries"; import {StatusBadge,PriorityBadge} from "../../components/badge";

type ActivityFilters={estado?:string;cliente?:string;creada_desde?:string;creada_hasta?:string;entrega_desde?:string;entrega_hasta?:string};

export default async function Activities({searchParams}:{searchParams:Promise<ActivityFilters>}){
  const filters=await searchParams;
  const clients=await query<any>("SELECT id,name FROM clients ORDER BY name");
  const conditions:string[]=[]; const args:string[]=[];
  if(["pending","in_progress","completed"].includes(filters.estado||"")){conditions.push("a.status=?");args.push(filters.estado as string);}
  if(filters.cliente&&/^\d+$/.test(filters.cliente)){conditions.push("a.client_id=?");args.push(filters.cliente);}
  if(filters.creada_desde){conditions.push("date(a.created_at)>=date(?)");args.push(filters.creada_desde);}
  if(filters.creada_hasta){conditions.push("date(a.created_at)<=date(?)");args.push(filters.creada_hasta);}
  if(filters.entrega_desde){conditions.push("date(a.due_date)>=date(?)");args.push(filters.entrega_desde);}
  if(filters.entrega_hasta){conditions.push("date(a.due_date)<=date(?)");args.push(filters.entrega_hasta);}
  const where=conditions.length?`WHERE ${conditions.join(" AND ")}`:"";
  const rows=await query<any>(`SELECT a.*,c.name client_name FROM activities a JOIN clients c ON c.id=a.client_id ${where} ORDER BY date(a.due_date),a.priority`,args);
  const hasFilters=conditions.length>0;
  return <div className="min-h-screen p-5 sm:p-8"><header className="mb-8 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-coral">Producción</p><h1 className="mt-2 text-3xl font-black">Actividades</h1><p className="mt-2 text-sm text-slate-500">Una bandeja de entrada para todo tu trabajo.</p></div><Link href="/actividades/nueva" className="btn bg-ink text-white"><Plus size={17}/> Nueva actividad</Link></header>
    <div className="card mb-6 p-5"><div className="mb-4 flex items-center gap-2 text-sm font-bold"><Filter size={17}/> Filtrar actividades</div><form method="get" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><div><label className="label">Estado</label><select name="estado" className="field" defaultValue={filters.estado||""}><option value="">Todos</option><option value="pending">Pendiente</option><option value="in_progress">En proceso</option><option value="completed">Finalizado</option></select></div><div><label className="label">Cliente</label><select name="cliente" className="field" defaultValue={filters.cliente||""}><option value="">Todos</option>{clients.map((client:any)=><option value={client.id} key={client.id}>{client.name}</option>)}</select></div><div><label className="label">Creada desde</label><input type="date" name="creada_desde" className="field" defaultValue={filters.creada_desde||""}/></div><div><label className="label">Creada hasta</label><input type="date" name="creada_hasta" className="field" defaultValue={filters.creada_hasta||""}/></div><div><label className="label">Entrega desde</label><input type="date" name="entrega_desde" className="field" defaultValue={filters.entrega_desde||""}/></div><div><label className="label">Entrega hasta</label><input type="date" name="entrega_hasta" className="field" defaultValue={filters.entrega_hasta||""}/></div><div className="flex items-end gap-2 sm:col-span-2 lg:col-span-3 xl:col-span-6"><button className="btn bg-ink text-white" type="submit"><Filter size={16}/> Aplicar filtros</button><Link className="btn border border-slate-200 bg-white" href="/actividades">Limpiar</Link></div></form></div>
    <div className="card overflow-hidden"><div className="flex items-center gap-2 border-b border-slate-100 p-4 text-sm text-slate-500"><CalendarDays size={16}/>{hasFilters?"Resultados filtrados":"Todas las actividades"}<span className="ml-auto text-xs text-slate-400">{rows.length} registros</span></div><div className="divide-y divide-slate-100">{rows.map((a:any)=>{const overdue=a.status!=="completed"&&a.status!=="cancelled"&&new Date(a.due_date)<new Date();return <Link href={`/actividades/${a.id}`} className="flex flex-wrap items-center gap-4 p-5 hover:bg-slate-50" key={a.id}><div className="min-w-[220px] flex-1"><div className="flex items-center gap-2"><h2 className="font-bold">{a.title}</h2>{overdue&&<span className="rounded-full bg-red-100 px-2 py-0.5 text-[10px] font-bold text-red-700">VENCIDA</span>}</div><p className="mt-1 text-xs text-slate-400">{a.client_name}</p><p className="mt-1 text-[11px] text-slate-400">Creada: {a.created_at?.slice(0,10)}</p></div><div className="w-28"><p className="text-[10px] uppercase text-slate-400">Entrega</p><p className={`mt-1 text-sm font-semibold ${overdue?"text-red-600":""}`}>{a.due_date}</p></div><div className="w-24"><PriorityBadge priority={a.priority}/></div><StatusBadge status={a.status}/></Link>})}{!rows.length&&<p className="p-12 text-center text-sm text-slate-400">{hasFilters?"No hay actividades que coincidan con esos filtros.":"Crea tu primera actividad."}</p>}</div></div></div>;
}
