import Link from "next/link"; import {CalendarDays,Filter} from "lucide-react"; import {query} from "../../lib/queries"; import {StatusBadge} from "../../components/badge";

type CalendarFilters={estado?:string;cliente?:string;asignado?:string;creada_desde?:string;creada_hasta?:string;entrega_desde?:string;entrega_hasta?:string};

export default async function Calendar({searchParams}:{searchParams:Promise<CalendarFilters>}){
  const filters=await searchParams;
  const clients=await query<any>("SELECT id,name FROM clients ORDER BY name"); const designers=await query<any>("SELECT name FROM designers ORDER BY name");
  const conditions:string[]=[]; const args:string[]=[];
  if(["pending","in_progress","review","completed","cancelled"].includes(filters.estado||"")){conditions.push("a.status=?");args.push(filters.estado as string);}
  if(filters.cliente&&/^\d+$/.test(filters.cliente)){conditions.push("a.client_id=?");args.push(filters.cliente);}
  if(filters.asignado){conditions.push("a.assigned_to=?");args.push(filters.asignado);}
  if(filters.creada_desde){conditions.push("date(a.created_at)>=date(?)");args.push(filters.creada_desde);}
  if(filters.creada_hasta){conditions.push("date(a.created_at)<=date(?)");args.push(filters.creada_hasta);}
  if(filters.entrega_desde){conditions.push("date(a.due_date)>=date(?)");args.push(filters.entrega_desde);}
  if(filters.entrega_hasta){conditions.push("date(a.due_date)<=date(?)");args.push(filters.entrega_hasta);}
  const where=conditions.length?`WHERE ${conditions.join(" AND ")}`:"";
  const rows=await query<any>(`SELECT a.*,c.name client_name FROM activities a JOIN clients c ON c.id=a.client_id ${where} ORDER BY date(a.due_date)`,args);
  const grouped=rows.reduce((o:any,a:any)=>{(o[a.due_date]??=[]).push(a);return o},{}); const hasFilters=conditions.length>0;
  return <div className="min-h-screen p-5 sm:p-8"><header className="mb-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-coral">Planificación</p><h1 className="mt-2 text-3xl font-black">Calendario</h1><p className="mt-2 text-sm text-slate-500">Tus entregas ordenadas por fecha.</p></header>
    <div className="card mb-6 p-5"><div className="mb-4 flex items-center gap-2 text-sm font-bold"><Filter size={17}/> Filtrar calendario</div><form method="get" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><div><label className="label">Estado</label><select name="estado" className="field" defaultValue={filters.estado||""}><option value="">Todos</option><option value="pending">Pendiente</option><option value="in_progress">En proceso</option><option value="review">En revisión</option><option value="completed">Finalizado</option><option value="cancelled">Cancelado</option></select></div><div><label className="label">Cliente</label><select name="cliente" className="field" defaultValue={filters.cliente||""}><option value="">Todos</option>{clients.map((client:any)=><option value={client.id} key={client.id}>{client.name}</option>)}</select></div><div><label className="label">Asignado a</label><select name="asignado" className="field" defaultValue={filters.asignado||""}><option value="">Todos</option>{designers.map((designer:any)=><option value={designer.name} key={designer.name}>{designer.name}</option>)}</select></div><div><label className="label">Creada desde</label><input type="date" name="creada_desde" className="field" defaultValue={filters.creada_desde||""}/></div><div><label className="label">Creada hasta</label><input type="date" name="creada_hasta" className="field" defaultValue={filters.creada_hasta||""}/></div><div><label className="label">Entrega desde</label><input type="date" name="entrega_desde" className="field" defaultValue={filters.entrega_desde||""}/></div><div><label className="label">Entrega hasta</label><input type="date" name="entrega_hasta" className="field" defaultValue={filters.entrega_hasta||""}/></div><div className="flex items-end gap-2 sm:col-span-2 lg:col-span-3 xl:col-span-6"><button className="btn bg-ink text-white" type="submit"><Filter size={16}/> Aplicar filtros</button><Link className="btn border border-slate-200 bg-white" href="/calendario">Limpiar</Link></div></form></div>
    <div className="mb-4 flex items-center gap-2 text-sm text-slate-500"><CalendarDays size={16}/>{hasFilters?"Resultados filtrados":"Todas las actividades"}<span className="text-xs text-slate-400">· {rows.length} registros</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(grouped).map(([day,acts]:any)=><div className="card p-5" key={day}><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{new Date(day+"T12:00:00").toLocaleDateString("es-CO",{weekday:"long",day:"numeric",month:"long"})}</p><div className="mt-4 space-y-2">{acts.map((a:any)=><Link href={`/actividades/${a.id}`} className="block rounded-xl border border-slate-100 p-3 hover:bg-slate-50" key={a.id}><p className="text-sm font-bold">{a.title}</p><p className="mt-1 text-xs text-slate-400">{a.client_name}</p><p className="mt-1 text-xs text-slate-400">Asignado a: {a.assigned_to||"Sin asignar"}</p><div className="mt-2"><StatusBadge status={a.status}/></div></Link>)}</div></div>)}{!rows.length&&<p className="text-sm text-slate-400">{hasFilters?"No hay actividades que coincidan con esos filtros.":"No hay actividades agendadas."}</p>}</div></div>;
}
