"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { db,initDb } from "../lib/db"; import { z } from "zod";
const clientSchema=z.object({name:z.string().trim().min(1,"El nombre es obligatorio"),company:z.string().optional(),phone:z.string().optional(),email:z.string().email("Correo inválido").or(z.literal("")),address:z.string().optional(),social_media:z.string().optional(),notes:z.string().optional()});
const activitySchema=z.object({client_id:z.coerce.number().positive(),title:z.string().trim().min(1),description:z.string().optional(),assigned_to:z.string().optional(),created_at:z.string().min(1),due_date:z.string().min(1),status:z.string(),priority:z.string(),comments:z.string().optional()});
export async function createClient(form:FormData){await initDb(); const v=clientSchema.parse(Object.fromEntries(form)); await db.execute({sql:"INSERT INTO clients (name,company,phone,email,address,social_media,notes) VALUES (?,?,?,?,?,?,?)",args:[v.name,v.company||null,v.phone||null,v.email||null,v.address||null,v.social_media||null,v.notes||null]}); revalidatePath("/"); revalidatePath("/clientes"); redirect("/clientes");}
export async function updateClient(id:number,form:FormData){await initDb(); const v=clientSchema.parse(Object.fromEntries(form)); await db.execute({sql:"UPDATE clients SET name=?,company=?,phone=?,email=?,address=?,social_media=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",args:[v.name,v.company||null,v.phone||null,v.email||null,v.address||null,v.social_media||null,v.notes||null,id]}); revalidatePath("/clientes"); redirect(`/clientes/${id}`);}
export async function deleteClient(id:number){await initDb(); const used=await db.execute({sql:"SELECT COUNT(*) count FROM activities WHERE client_id=?",args:[id]}); if(Number(used.rows[0].count)>0) throw new Error("No se puede eliminar un cliente con actividades asociadas."); await db.execute({sql:"DELETE FROM clients WHERE id=?",args:[id]}); revalidatePath("/clientes");}
export async function createActivity(form:FormData){await initDb(); const v=activitySchema.parse(Object.fromEntries(form)); const r=await db.execute({sql:"INSERT INTO activities (client_id,title,description,assigned_to,created_at,due_date,status,priority,comments) VALUES (?,?,?,?,?,?,?,?,?)",args:[v.client_id,v.title,v.description||null,v.assigned_to||null,v.created_at,v.due_date,v.status,v.priority,v.comments||null]}); revalidatePath("/"); revalidatePath("/actividades"); redirect(`/actividades/${r.lastInsertRowid}`);}
export async function updateActivity(id:number,form:FormData){await initDb(); const v=activitySchema.parse(Object.fromEntries(form)); await db.execute({sql:"UPDATE activities SET client_id=?,title=?,description=?,assigned_to=?,created_at=?,due_date=?,status=?,priority=?,comments=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",args:[v.client_id,v.title,v.description||null,v.assigned_to||null,v.created_at,v.due_date,v.status,v.priority,v.comments||null,id]}); revalidatePath("/"); revalidatePath("/actividades"); redirect(`/actividades/${id}`);}
export async function deleteActivity(id:number){await initDb(); await db.execute({sql:"DELETE FROM activities WHERE id=?",args:[id]}); revalidatePath("/"); revalidatePath("/actividades"); redirect("/actividades");}
export async function addUpdate(activityId:number,form:FormData){await initDb(); const comment=String(form.get("comment")||"").trim(); const status=String(form.get("status")||"pending"); if(!comment) throw new Error("Escribe un comentario"); await db.batch([{sql:"INSERT INTO activity_updates (activity_id,comment,status) VALUES (?,?,?)",args:[activityId,comment,status]},{sql:"UPDATE activities SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",args:[status,activityId]}],"write"); revalidatePath(`/actividades/${activityId}`);}
export async function updateSettings(form:FormData){await initDb(); const keys=["designer_name","designer_email","studio_name","studio_address","studio_social","date_format","notify_due","notify_overdue"]; await db.batch(keys.map(key=>({sql:"INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP",args:[key,String(form.get(key)||"")]})),"write"); revalidatePath("/configuracion");}
export async function createDesigner(form:FormData){await initDb(); const name=String(form.get("name")||"").trim(); if(!name) throw new Error("El nombre es obligatorio"); await db.execute({sql:"INSERT INTO designers (name,email,role) VALUES (?,?,?)",args:[name,String(form.get("email")||"")||null,String(form.get("role")||"")||null]}); revalidatePath("/configuracion"); revalidatePath("/actividades/nueva");}
